# Generated by Django 4.1.1 on 2023-01-02 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_good_to_have_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='good_to_have_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='primary_skills',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='secondary_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
