# Generated by Django 4.1.1 on 2023-01-02 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_good_to_have_skills_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='mininum_experience',
            new_name='minimum_experience',
        ),
    ]
