# Generated by Django 4.1.1 on 2023-01-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='specialty',
            new_name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, choices=[('entry_level', 'Entry Level'), ('mid_level', 'Mid Level'), ('senior', 'Senior')], max_length=255, null=True),
        ),
    ]
