# Generated by Django 4.1.1 on 2023-01-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='years_of_experience',
            field=models.FloatField(default=0),
        ),
    ]
