# Generated by Django 4.1.1 on 2023-01-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0002_education_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='professional_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
