# Generated by Django 4.1.1 on 2023-01-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0003_candidate_professional_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
