# Generated by Django 4.1.1 on 2023-01-02 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0007_skill_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='years_of_experience',
        ),
    ]
