# Generated by Django 4.1.1 on 2023-01-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0008_remove_education_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
