# Generated by Django 4.1.1 on 2023-01-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0009_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
